customer_status_int = {
    "CUSTOMER_STATUS_UNSPECIFIED": 0,
    "CUSTOMER_STATUS_POTENTIAL": 1,
    "CUSTOMER_STATUS_ACTIVE": 2,
    "CUSTOMER_STATUS_BLOCKED": 3,
    "CUSTOMER_STATUS_TERMINATED": 4,
    "CUSTOMER_STATUS_SUSPEND": 5
}

customer_state_int = {
    "CUSTOMER_STATE_UNKNOWN": 0,
    "CUSTOMER_STATE_ACTIVE": 1,
    "CUSTOMER_STATE_BLOCKED": 2,
    "CUSTOMER_STATE_TERMINATED": 3
}

terminator_state_attr_int = {
    "TERMINATOR_UNKNOWN": 0,
    'TERMINATOR_SYSTEM': 1,
    "TERMINATOR_CLIENT": 2
}

customer_type_int = {
    "CUSTOMER_TYPE_UNSPECIFIED": 0,
    "CUSTOMER_TYPE_PHYSICAL": 1,
    "CUSTOMER_TYPE_ENTREPRENEUR": 2,
    "CUSTOMER_TYPE_JURIDICAL": 3,
}

customer_sign_type_int = {
    "CUSTOMER_SIGN_TYPE_UNSPECIFIED": 0,
    "CUSTOMER_SIGN_TYPE_PAPER": 1,
    "CUSTOMER_SIGN_TYPE_GOS": 2,
    "CUSTOMER_SIGN_TYPE_EDO": 3
}

customer_verification_status_int = {
    "CUSTOMER_VERIFICATION_STATUS_UNSPECIFIED": 0,
    "CUSTOMER_VERIFICATION_STATUS_IN_PROGRESS": 1,
    "CUSTOMER_VERIFICATION_STATUS_FAILED": 2,
    "CUSTOMER_VERIFICATION_STATUS_REJECTED": 3,
    "CUSTOMER_VERIFICATION_STATUS_SUCCESS": 4
}

contract_type_int = {
    "CONTRACT_TYPE_UNSPECIFIED": 0,
    "CONTRACT_TYPE_PAPER": 1,
    "CONTRACT_TYPE_GOS": 2,
    "CONTRACT_TYPE_EDO": 3
}

contract_status_int = {
    "CONTRACT_STATUS_UNSPECIFIED": 0,
    "CONTRACT_STATUS_NOT_SIGNED": 1,
    "CONTRACT_STATUS_IN_PROGRESS": 2,
    "CONTRACT_STATUS_SIGNED": 3,
    "CONTRACT_STATUS_TERMINATED": 4,
    "CONTRACT_STATUS_FAILED": 5,
}

contract_payment_type_int = {
    "CONTRACT_PAYMENT_TYPE_UNSPECIFIED": 0,
    "CONTRACT_PAYMENT_TYPE_CREDIT": 1,
    "CONTRACT_PAYMENT_TYPE_ADVANCE": 2,
}

personal_doc_type_int = {
    "PERSONAL_DOC_TYPE_NONE": 0,
    "PERSONAL_DOC_TYPE_PASSPORT_RF": 1
}

verify_slot_status_int = {
    "VERIFY_SLOT_STATUS_UNSPECIFIED": 0,
    "VERIFY_SLOT_STATUS_NEW": 1,
    "VERIFY_SLOT_STATUS_IN_PROGRESS": 2,
    "VERIFY_SLOT_STATUS_SUCCESS": 3,
    "VERIFY_SLOT_STATUS_REJECTED": 4
}
